FROM ubuntu:latest

RUN useradd britbus
USER britbus

RUN apt-get update && apt-get install ca-certificates -y && update-ca-certificates

WORKDIR /

COPY ./data-importer /data-importer

RUN chmod +x /data-importer

ENTRYPOINT ["/data-importer"]