FROM ubuntu:latest

RUN addgroup -S britbus && adduser --system britbus -G britbus
USER britbus

RUN apt-get update && apt-get install ca-certificates -y && update-ca-certificates

WORKDIR /

COPY ./web-api /web-api

RUN chmod +x /web-api

EXPOSE 80

ENTRYPOINT ["/web-api", "run", "--listen", ":80"]
