FROM ubuntu:latest

RUN addgroup -S britbus && adduser --system britbus -G britbus
USER britbus

RUN apt-get update && apt-get install ca-certificates -y && update-ca-certificates

WORKDIR /

COPY ./realtime /realtime

RUN chmod +x /realtime

EXPOSE 3333

ENTRYPOINT ["/realtime"]