FROM ubuntu:latest

RUN apt-get update && apt-get install ca-certificates -y && update-ca-certificates

WORKDIR /

COPY ./stats /stats
COPY ./transforms /transforms

RUN chmod +x /stats

RUN useradd travigo
USER travigo

ENTRYPOINT ["/stats"]