FROM ubuntu:latest

RUN apt-get update && apt-get install ca-certificates -y && update-ca-certificates

RUN useradd britbus
USER britbus

WORKDIR /

COPY ./realtime /realtime

RUN chmod +x /realtime

EXPOSE 3333

ENTRYPOINT ["/realtime"]