FROM ubuntu:latest

RUN apt-get update && apt-get install ca-certificates -y && update-ca-certificates

WORKDIR /

COPY ./data-importer /data-importer

RUN chmod +x /data-importer

RUN useradd travigo
USER travigo

ENTRYPOINT ["/data-importer"]