FROM ubuntu:latest

RUN apt-get update && apt-get install ca-certificates -y && update-ca-certificates

RUN useradd britbus
USER britbus

WORKDIR /

COPY ./web-api /web-api

RUN chmod +x /web-api

EXPOSE 80

ENTRYPOINT ["/web-api", "run", "--listen", ":80"]
