# Default values for travigo-web-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: ghcr.io/travigo/travigo
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: main

database:
  connectionStringSecret: travigo-mongodb-admin-travigo
  database: travigo
  realtime:
    connectionStringSecret: travigo-realtime-mongodb-travigo
    database: travigo

elasticsearch:
  address: "https://primary-es-http.elastic:9200"
  accountSecret: "travigo-elasticsearch-user"

redis:
  address: "redis-headless.redis:6379"
  passwordSecret: redis-password

bods:
  apiKeySecret: travigo-bods-api

tfl:
  apiKeySecret: travigo-tfl-api-key

auth:
  domain: travigo.uk.auth0.com
  audience: https://api-travigo.claydonlee.com

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://travigo.claydonlee.com,https://www-travigo.claydonlee.com,https://web-travigo.claydonlee.com"
  hosts:
    - host: api-travigo.claydonlee.com
      paths:
        - path: /core
          pathType: ImplementationSpecific


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
