image:
  args:
  - events
  - run

replicaCount: 3

ingress:
  enabled: true
  hosts:
    - host: api.travigo.app
      paths:
        - path: /events-queue
          pathType: ImplementationSpecific

resources:
  requests:
    cpu: 200m
    memory: 256Mi